# Generated by Django 5.1.7 on 2025-05-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='usuario',
        ),
    ]
