# Generated by Django 5.1.7 on 2025-04-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
        ('reportes', '0002_alter_reporte_programacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='programacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='programacion.programacion'),
        ),
    ]
