# Generated by Django 5.1.7 on 2025-05-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='capacidad',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='jornada',
            field=models.CharField(choices=[('diurna', 'Diurna'), ('tarde', 'Tarde'), ('nocturna', 'Nocturna'), ('mixta', 'Mixta')], default='diurna', max_length=15),
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa',
            field=models.CharField(default='ADSO', max_length=70),
            preserve_default=False,
        ),
    ]
