# Generated by Django 5.1.7 on 2025-04-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='celular',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('seguridad', 'Guardia'), ('aseo', 'Limpieza')], default='seguridad', max_length=10),
        ),
    ]
