# Generated by Django 5.1.7 on 2025-04-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_fecha_registro_alter_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
    ]
