# Generated by Django 5.1.7 on 2025-05-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usuario_first_name_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='face_token',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('seguridad', 'Guardia'), ('aseo', 'Limpieza')], default='instructor', max_length=20),
        ),
    ]
